repos:
  - repo: local
    hooks:
      - id: jq-notebook-clean
        name: Clean Jupyter Notebooks
        language: system
        entry: |
          jq --indent 1 -i '
            (.cells[] | select(has("execution_count"))).execution_count = null |
            (.cells[] | select(has("id"))).id = null |
            del(.metadata.kernelspec?.display_name?,
                .metadata.language_info?.version?)
          '
        files: \.ipynb$
        pass_filenames: true
        types_or: [file]
